project:
  type: website
  output-dir: _site

website:
  site-url: https://blog.zarathu.com
  repo-url: https://github.com/zarathucorp/blog
  title: "Zarathu Blog"
  description: "News, insights, and in-depth case studies from Zarathu"
  favicon: img/logo_favicon.png
  google-analytics: "UA-135478021-2"
  page-navigation: true
  page-footer:
    background: "#0F2E3D"
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2019. [Zarathu Co.,Ltd.](https://www.zarathu.com) All rights reserved.
      Licence: [MIT](https://opensource.org/license/mit-0/).
    border: true
  search:
    location: navbar
    type: overlay
  navbar:
    background: "#0F2E3D"
    logo: img/logo.png
    right:
    - text: "Home"
      href: index.html
    - text: "Applications"
      href: http://app.zarathu.com/
    - text: R packages
      menu:
      - text: jstable      
        href: https://jinseob2kim.github.io/jstable/
      - text: jskm
        href: https://jinseob2kim.github.io/jskm/
      - text: jsmodule
        href: https://jinseob2kim.github.io/jsmodule/
    - text: Contributors
      href: contributors.qmd
    - text: Partners
      menu:
        - text: <img src='https://www.r-bloggers.com/favicon.ico'>  R-bloggers
          href: https://www.r-bloggers.com/
        - text: <img width = '16px' src='https://avatars.githubusercontent.com/u/46996346?s=200&v=4'> Shinykorea
          href: https://github.com/shinykorea/
    - icon: github
      href: https://github.com/zarathucorp
    - icon: linkedin
      href: https://www.linkedin.com/company/zarathu/
    - icon: rss
      href: index.xml
      aria-label: RSS
  
format:
  html:
    smooth-scroll: true
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: "left"
    code-link: true
    highlight-style: github
    citation-location: document
    citation: true
    citeproc: true
    reference-location: document
    footnotes-hover: true

comments: 
  giscus: 
    repo: zarathucorp/giscus-blog
