project:
  type: website

profile:
  default: ko
  group: [ko, en, jp]

format:
  html:
    smooth-scroll: true
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: "left"
    code-link: true
    highlight-style: github
    citation-location: document
    citation: true
    citeproc: true
    reference-location: document
    footnotes-hover: true
    include-before-body: gtag.html

comments: 
  giscus: 
    repo: zarathucorp/giscus-blog
