project:
  type: website
  output-dir: _site

website:
  site-url: https://blog.zarathu.com
  repo-url: https://github.com/zarathucorp/blog
  title: "Zarathu Blog"
  description: "News, insights, and in-depth case studies from Zarathu"
  favicon: img/logo_favicon.png
  google-analytics: "UA-135478021-2"
  page-navigation: true
  page-footer:
    background: "#0F2E3D"
    center: 
      - text: © Copyright 2019 Zarathu Co.,Ltd.
        href: https://www.zarathu.com
      - text: Software licensed under the MIT License.
        href: https://raw.githubusercontent.com/zarathucorp/blog/master/LICENSE
  search:
    location: navbar
    type: overlay
  navbar:
    background: "#0F2E3D"
    logo: img/logo.png
    right:
          - text: "Home"
            href: index.html
          - text: "Applications"
            href: http://app.zarathu.com/
          - text: R packages
            menu:
            - text: jstable      
              href: https://jinseob2kim.github.io/jstable/
            - text: jskm
              href: https://jinseob2kim.github.io/jskm/
            - text: jsmodule
              href: https://jinseob2kim.github.io/jsmodule/
          - contributors.qmd
          - icon: github
            href: https://github.com/zarathucorp
          - icon: rss
            href: index.xml
            aria-label: RSS
  
format:
  html:
    smooth-scroll: true
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: "left"
    code-link: true
    highlight-style: github
    citation-location: document
    citation: true
    citeproc: true
    reference-location: document
    footnotes-hover: true

    
editor: visual


comments: 
  giscus: 
    repo: zarathucorp/giscus-blog
